2025-08-13 13:59:53,302 INFO Transaction received from 192.168.138.166: {'id': 93932, 'first_name': 'James', 'last_name': 'Johnson', 'phone': '+254657445678', 'amount': 4.0, 'payment_option': 'Visa', 'transaction_date': '2022-02-04T14:19:05.0210431Z', 'currency': 'KES', 'merchant_reference': 'kxcs8e', 'confirmation_code': 'X0ISJS00WS'}
2025-08-13 13:59:54,052 ERROR Error saving transaction to DB
Traceback (most recent call last):
  File "C:\Users\MichaelAkoko\OneDrive - pesapal.com\Documents\Michael-Akoko-Projects\pesapal-wireless-pos-callback-endpoint\callback_listener\app.py", line 222, in pesapal_callback
    save_transaction_to_db(data)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\MichaelAkoko\OneDrive - pesapal.com\Documents\Michael-Akoko-Projects\pesapal-wireless-pos-callback-endpoint\callback_listener\db.py", line 111, in save_transaction_to_db
    conn = get_connection()
  File "C:\Users\MichaelAkoko\OneDrive - pesapal.com\Documents\Michael-Akoko-Projects\pesapal-wireless-pos-callback-endpoint\callback_listener\db.py", line 45, in get_connection
    return pyodbc.connect(conn_str)
           ~~~~~~~~~~~~~~^^^^^^^^^^
pyodbc.Error: ('HY000', '[HY000] [Microsoft][ODBC Driver 17 for SQL Server]Protocol error in TDS stream (0) (SQLDriverConnect); [HY000] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection due to prelogin failure (0)')
2025-08-13 13:59:54,058 INFO 192.168.138.166 - - [13/Aug/2025 13:59:54] "[35m[1mPOST /pesapal-callback HTTP/1.1[0m" 500 -
2025-08-13 14:03:03,841 INFO Transaction received from 192.168.138.166: {'id': 97532, 'first_name': 'James', 'last_name': 'Johnson', 'phone': '+254657445678', 'amount': 4.0, 'payment_option': 'Visa', 'transaction_date': '2022-02-04T14:19:05.0210431Z', 'currency': 'KES', 'merchant_reference': 'kxcs8e', 'confirmation_code': 'X0ISJS00WS'}
2025-08-13 14:03:04,457 ERROR Error saving transaction to DB
Traceback (most recent call last):
  File "C:\Users\MichaelAkoko\OneDrive - pesapal.com\Documents\Michael-Akoko-Projects\pesapal-wireless-pos-callback-endpoint\callback_listener\app.py", line 222, in pesapal_callback
    save_transaction_to_db(data)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\MichaelAkoko\OneDrive - pesapal.com\Documents\Michael-Akoko-Projects\pesapal-wireless-pos-callback-endpoint\callback_listener\db.py", line 111, in save_transaction_to_db
    conn = get_connection()
  File "C:\Users\MichaelAkoko\OneDrive - pesapal.com\Documents\Michael-Akoko-Projects\pesapal-wireless-pos-callback-endpoint\callback_listener\db.py", line 45, in get_connection
    return pyodbc.connect(conn_str)
           ~~~~~~~~~~~~~~^^^^^^^^^^
pyodbc.Error: ('HY000', '[HY000] [Microsoft][ODBC Driver 17 for SQL Server]Protocol error in TDS stream (0) (SQLDriverConnect); [HY000] [Microsoft][ODBC Driver 17 for SQL Server]Client unable to establish connection due to prelogin failure (0)')
2025-08-13 14:03:04,458 INFO 192.168.138.166 - - [13/Aug/2025 14:03:04] "[35m[1mPOST /pesapal-callback HTTP/1.1[0m" 500 -
